# DATA SOURCE
DATA_SOURCE          = "conllu"    # "conllu" (real DCS) | "synthetic" (demo)
CONLLU_ROOT          = "../dataset_files"  # path to DCS
OUTPUT_DIR           = "../outputs" # all plots and CSVs saved here
MAX_TEXTS_PER_GENRE  = None        # None = load all texts; int = cap per genre
RANDOM_SEED          = 42

# GENRE LABELS AND PALETTE
GENRES = ["Epic", "Vedic", "Kavya", "Shastra", "Puranic"]

GENRE_PALETTE = {
    "Epic"    : "#E63946",
    "Vedic"   : "#2A9D8F",
    "Kavya"   : "#E9C46A",
    "Shastra" : "#457B9D",
    "Puranic" : "#F4A261",
}

# MORPHOLOGICAL FEATURE TAGS
CASE_TAGS  = ["Nom", "Acc", "Inst", "Dat", "Abl", "Gen", "Loc", "Voc"]
TENSE_TAGS = ["Pres", "Past", "Fut", "Imp"]
MOOD_TAGS  = ["Ind", "Opt", "Imp", "Sub"]
POS_TAGS   = ["NOUN", "VERB", "ADJ", "ADP", "PRON", "NUM", "ADV", "PART"]

# GENRE MAP — exact IAST folder names from the DCS 'files/' directory
# Maps each text folder name to one of the 5 genre labels above.
GENRE_MAP = {

    # ── EPIC ──
    "Mahābhārata"                       : "Epic",
    "Rāmāyaṇa"                          : "Epic",
    "Harivaṃśa"                         : "Epic",
    "Bhāratamañjarī"                    : "Epic",

    # ── VEDIC ──
    # Samhitas
    "Ṛgveda"                            : "Vedic",
    "Ṛgvedakhilāni"                     : "Vedic",
    "Atharvaveda (Paippalāda)"          : "Vedic",
    "Atharvaveda (Śaunaka)"             : "Vedic",
    "Atharvavedapariśiṣṭa"             : "Vedic",
    "Maitrāyaṇīsaṃhitā"                : "Vedic",
    "Kāṭhakasaṃhitā"                   : "Vedic",
    "Vājasaneyisaṃhitā (Mādhyandina)"  : "Vedic",
    # Brahmanas
    "Aitareyabrāhmaṇa"                  : "Vedic",
    "Gopathabrāhmaṇa"                   : "Vedic",
    "Jaiminīyabrāhmaṇa"                 : "Vedic",
    "Jaiminīya-Upaniṣad-Brāhmaṇa"      : "Vedic",
    "Kauṣītakibrāhmaṇa"                 : "Vedic",
    "Pañcaviṃśabrāhmaṇa"               : "Vedic",
    "Sāmavidhānabrāhmaṇa"              : "Vedic",
    "Śatapathabrāhmaṇa"                 : "Vedic",
    "Ṣaḍviṃśabrāhmaṇa"                 : "Vedic",
    # Aranyakas
    "Aitareya-Āraṇyaka"                 : "Vedic",
    "Kaṭhāraṇyaka"                      : "Vedic",
    "Śāṅkhāyanāraṇyaka"                 : "Vedic",
    "Taittirīyāraṇyaka"                 : "Vedic",
    # Upanishads
    "Aitareyopaniṣad"                   : "Vedic",
    "Amṛtabindūpaniṣat"                 : "Vedic",
    "Atharvaprāyaścittāni"              : "Vedic",
    "Brahmabindūpaniṣat"                : "Vedic",
    "Bṛhadāraṇyakopaniṣad"             : "Vedic",
    "Chāndogyopaniṣad"                  : "Vedic",
    "Garbhopaniṣat"                     : "Vedic",
    "Kauṣītakyupaniṣad"                 : "Vedic",
    "Kaṭhopaniṣad"                      : "Vedic",
    "Muṇḍakopaniṣad"                    : "Vedic",
    "Nādabindūpaniṣat"                  : "Vedic",
    "Śvetāśvataropaniṣad"               : "Vedic",
    "Śira'upaniṣad"                     : "Vedic",
    "Taittirīyopaniṣad"                 : "Vedic",
    "Taittirīyabrāhmaṇa"                : "Vedic",
    "Taittirīyasaṃhitā"                 : "Vedic",
    # Grhya / Shrauta / Dharmasutras
    "Āpastambadharmasūtra"              : "Vedic",
    "Āpastambagṛhyasūtra"               : "Vedic",
    "Āpastambaśrautasūtra"              : "Vedic",
    "Āśvalāyanagṛhyasūtra"              : "Vedic",
    "Āśvālāyanaśrautasūtra"             : "Vedic",
    "Baudhāyanadharmasūtra"             : "Vedic",
    "Baudhāyanagṛhyasūtra"              : "Vedic",
    "Baudhāyanaśrautasūtra"             : "Vedic",
    "Bhāradvājagṛhyasūtra"              : "Vedic",
    "Bhāradvājaśrautasūtra"             : "Vedic",
    "Drāhyāyaṇaśrautasūtra"            : "Vedic",
    "Gobhilagṛhyasūtra"                 : "Vedic",
    "Gautamadharmasūtra"                : "Vedic",
    "Hiraṇyakeśigṛhyasūtra"            : "Vedic",
    "Hiraṇyakeśiśrautasūtra"           : "Vedic",
    "Jaiminigṛhyasūtra"                 : "Vedic",
    "Jaiminīyaśrautasūtra"              : "Vedic",
    "Kauśikasūtra"                      : "Vedic",
    "Kauśikasūtradārilabhāṣya"         : "Vedic",
    "Kauśikasūtrakeśavapaddhati"       : "Vedic",
    "Kauṣītakagṛhyasūtra"              : "Vedic",
    "Kātyāyanaśrautasūtra"              : "Vedic",
    "Kāṭhakagṛhyasūtra"                : "Vedic",
    "Khādiragṛhyasūtra"                 : "Vedic",
    "Mānavagṛhyasūtra"                  : "Vedic",
    "Mānavaśrautasūtra"                 : "Vedic",
    "Pāraskaragṛhyasūtra"               : "Vedic",
    "Śāṅkhāyanagṛhyasūtra"              : "Vedic",
    "Śāṅkhāyanaśrautasūtra"             : "Vedic",
    "Vaikhānasadharmasūtra"             : "Vedic",
    "Vaikhānasagṛhyasūtra"              : "Vedic",
    "Vaikhānasaśrautasūtra"             : "Vedic",
    "Vaitānasūtra"                      : "Vedic",
    "Vasiṣṭhadharmasūtra"               : "Vedic",
    "Vārāhagṛhyasūtra"                  : "Vedic",
    "Vārāhaśrautasūtra"                 : "Vedic",
    # Vedanga
    "Nirukta"                           : "Vedic",
    "Ṛgvedavedāṅgajyotiṣa"             : "Vedic",
    "Ṛgvidhāna"                         : "Vedic",

    # ── KAVYA ──
    "Acintyastava"                      : "Kavya",
    "Amaruśataka"                       : "Kavya",
    "Āryāsaptaśatī"                     : "Kavya",
    "Avadānaśataka"                     : "Kavya",
    "Aṣṭasāhasrikā"                     : "Kavya",
    "Aṣṭāvakragīta"                     : "Kavya",
    "Bhadrabāhucarita"                  : "Kavya",
    "Bhairavastava"                     : "Kavya",
    "Bhallaṭaśataka"                    : "Kavya",
    "Bhramarāṣṭaka"                     : "Kavya",
    "Bodhicaryāvatāra"                  : "Kavya",
    "Bṛhatkathāślokasaṃgraha"          : "Kavya",
    "Buddhacarita"                      : "Kavya",
    "Caurapañcaśikā"                    : "Kavya",
    "Daśakumāracarita"                  : "Kavya",
    "Devīmāhātmya"                      : "Kavya",
    "Divyāvadāna"                       : "Kavya",
    "Gītagovinda"                       : "Kavya",
    "Haribhaktivilāsa"                  : "Kavya",
    "Harṣacarita"                       : "Kavya",
    "Haṃsadūta"                         : "Kavya",
    "Haṃsasaṃdeśa"                      : "Kavya",
    "Hitopadeśa"                        : "Kavya",
    "Kathāsaritsāgara"                  : "Kavya",
    "Kirātārjunīya"                     : "Kavya",
    "Kokilasaṃdeśa"                     : "Kavya",
    "Kumārasaṃbhava"                    : "Kavya",
    "Kādambarīsvīkaraṇasūtramañjarī"   : "Kavya",
    "Lalitavistara"                     : "Kavya",
    "Laṅkāvatārasūtra"                  : "Kavya",
    "Meghadūta"                         : "Kavya",
    "Mukundamālā"                       : "Kavya",
    "Narmamālā"                         : "Kavya",
    "Rasikapriyā"                       : "Kavya",
    "Rasikasaṃjīvanī"                   : "Kavya",
    "Ṛtusaṃhāra"                        : "Kavya",
    "Saddharmapuṇḍarīkasūtra"          : "Kavya",
    "Saṅghabhedavastu"                  : "Kavya",
    "Saundarānanda"                     : "Kavya",
    "Śatakatraya"                       : "Kavya",
    "Śikṣāsamuccaya"                    : "Kavya",
    "Śukasaptati"                       : "Kavya",
    "Smaradīpikā"                       : "Kavya",
    "Sūryaśataka"                       : "Kavya",
    "Tantrākhyāyikā"                    : "Kavya",
    "Ṭikanikayātrā"                     : "Kavya",
    "Vetālapañcaviṃśatikā"              : "Kavya",

    # ── SHASTRA ──
    # Grammar
    "Aṣṭādhyāyī"                        : "Shastra",
    "Kāśikāvṛtti"                       : "Shastra",
    "Kāvyālaṃkāra"                      : "Shastra",
    "Kāvyālaṃkāravṛtti"                 : "Shastra",
    "Kāvyādarśa"                        : "Shastra",
    # Lexicography
    "Abhidhānacintāmaṇi"                : "Shastra",
    "Abhinavacintāmaṇi"                 : "Shastra",
    "Agastīyaratnaparīkṣā"             : "Shastra",
    "Amarakośa"                         : "Shastra",
    "Amaraughaśāsana"                   : "Shastra",
    "Aṣṭāṅganighaṇṭu"                   : "Shastra",
    "Bījanighaṇṭu"                      : "Shastra",
    "Dhanvantarinighaṇṭu"               : "Shastra",
    "Kaiyadevanighaṇṭu"                 : "Shastra",
    "Madanapālanighaṇṭu"                : "Shastra",
    "Nighaṇṭuśeṣa"                      : "Shastra",
    "Rājanighaṇṭu"                      : "Shastra",
    "Trikāṇḍaśeṣa"                      : "Shastra",
    # Dharmashastra
    "Arthaśāstra"                       : "Shastra",
    "Kāmasūtra"                         : "Shastra",
    "Kātyāyanasmṛti"                    : "Shastra",
    "Manusmṛti"                         : "Shastra",
    "Nāradasmṛti"                       : "Shastra",
    "Parāśaradharmasaṃhitā"            : "Shastra",
    "Parāśarasmṛtiṭīkā"                : "Shastra",
    "Viṣṇusmṛti"                        : "Shastra",
    "Vṛddhayamasmṛti"                   : "Shastra",
    "Yājñavalkyasmṛti"                  : "Shastra",
    "Gṛhastharatnākara"                 : "Shastra",
    "Nibandhasaṃgraha"                  : "Shastra",
    # Ayurveda
    "Aṣṭāṅgahṛdayasaṃhitā"             : "Shastra",
    "Aṣṭāṅgasaṃgraha"                   : "Shastra",
    "Ayurvedarasāyana"                  : "Shastra",
    "Āyurvedadīpikā"                    : "Shastra",
    "Bhāvaprakāśa"                      : "Shastra",
    "Carakasaṃhitā"                     : "Shastra",
    "Carakatattvapradīpikā"             : "Shastra",
    "Indu (ad AHS)"                     : "Shastra",
    "Nāḍīparīkṣā"                       : "Shastra",
    "Sarvāṅgasundarā"                   : "Shastra",
    "Suśrutasaṃhitā"                    : "Shastra",
    "Śārṅgadharasaṃhitā"                : "Shastra",
    "Śārṅgadharasaṃhitādīpikā"         : "Shastra",
    # Rasa / Alchemy
    "Ānandakanda"                       : "Shastra",
    "Rasahṛdayatantra"                  : "Shastra",
    "Rasakāmadhenu"                     : "Shastra",
    "Rasamañjarī"                       : "Shastra",
    "Rasaprakāśasudhākara"              : "Shastra",
    "Rasaratnasamuccaya"                : "Shastra",
    "Rasaratnasamuccayabodhinī"         : "Shastra",
    "Rasaratnasamuccayadīpikā"         : "Shastra",
    "Rasaratnasamuccayaṭīkā"           : "Shastra",
    "Rasaratnākara"                     : "Shastra",
    "Rasasaṃketakalikā"                 : "Shastra",
    "Rasataraṅgiṇī"                     : "Shastra",
    "Rasendracintāmaṇi"                 : "Shastra",
    "Rasendracūḍāmaṇi"                  : "Shastra",
    "Rasendrasārasaṃgraha"              : "Shastra",
    "Rasādhyāya"                        : "Shastra",
    "Rasādhyāyaṭīkā"                    : "Shastra",
    "Rasārṇava"                         : "Shastra",
    "Rasārṇavakalpa"                    : "Shastra",
    "Ratnadīpikā"                       : "Shastra",
    "Ratnaṭīkā"                         : "Shastra",
    "Yogaratnākara"                     : "Shastra",
    # Philosophy
    "Abhidharmakośa"                    : "Shastra",
    "Abhidharmakośabhāṣya"              : "Shastra",
    "Gaṇakārikā"                        : "Shastra",
    "Janmamaraṇavicāra"                 : "Shastra",
    "Mīmāṃsāsūtrabhāṣya"               : "Shastra",
    "Mugdhāvabodhinī"                   : "Shastra",
    "Mūlamadhyamakārikāḥ"              : "Shastra",
    "Nyāyabhāṣya"                       : "Shastra",
    "Nyāyabindu"                        : "Shastra",
    "Nyāyasūtra"                        : "Shastra",
    "Padārthacandrikā"                  : "Shastra",
    "Pañcārthabhāṣya"                   : "Shastra",
    "Prasannapadā"                      : "Shastra",
    "Sarvadarśanasaṃgraha"             : "Shastra",
    "Saṃvitsiddhi"                      : "Shastra",
    "Sāṃkhyakārikā"                     : "Shastra",
    "Sāṃkhyakārikābhāṣya"              : "Shastra",
    "Sāṃkhyatattvakaumudī"              : "Shastra",
    "Spandakārikā"                      : "Shastra",
    "Spandakārikānirṇaya"               : "Shastra",
    "Tarkasaṃgraha"                     : "Shastra",
    "Tattvavaiśāradī"                   : "Shastra",
    "Vaiśeṣikasūtra"                    : "Shastra",
    "Vaiśeṣikasūtravṛtti"               : "Shastra",
    "Viṃśatikākārikā"                   : "Shastra",
    "Viṃśatikāvṛtti"                    : "Shastra",
    "Yogasūtra"                         : "Shastra",
    "Yogasūtrabhāṣya"                   : "Shastra",
    "Sphuṭārthāvyākhyā"                 : "Shastra",
    "Gūḍhārthadīpikā"                   : "Shastra",
    # Poetics
    "Nāṭyaśāstra"                       : "Shastra",
    "Nāṭyaśāstravivṛti"                 : "Shastra",
    "Rājamārtaṇḍa"                      : "Shastra",
    # Astronomy
    "Sūryasiddhānta"                    : "Shastra",
    "Sūryaśatakaṭīkā"                   : "Shastra",
    # Technical
    "Dhanurveda"                        : "Shastra",
    "Kṛṣiparāśara"                      : "Shastra",
    "Śyainikaśāstra"                    : "Shastra",
    # Commentaries
    "Commentary on Amaraughaśāsana"                    : "Shastra",
    "Commentary on the Kādambarīsvīkaraṇasūtramañjarī": "Shastra",
    "Commentary on the Kāvyālaṃkāravṛtti"             : "Shastra",
    # Tantra (grouped under Shastra; rename to "Tantra" for 6-genre analysis)
    "Gheraṇḍasaṃhitā"                   : "Shastra",
    "Gorakṣaśataka"                     : "Shastra",
    "Haṭhayogapradīpikā"                : "Shastra",
    "Mahācīnatantra"                    : "Shastra",
    "Mātṛkābhedatantra"                 : "Shastra",
    "Mṛgendratantra"                    : "Shastra",
    "Mṛgendraṭīkā"                      : "Shastra",
    "Paramānandīyanāmamālā"             : "Shastra",
    "Paraśurāmakalpasūtra"              : "Shastra",
    "Pāśupatasūtra"                     : "Shastra",
    "Sātvatatantra"                     : "Shastra",
    "Śivasūtra"                         : "Shastra",
    "Śivasūtravārtika"                  : "Shastra",
    "Śāktavijñāna"                      : "Shastra",
    "Tantrasāra"                        : "Shastra",
    "Tantrāloka"                        : "Shastra",
    "Toḍalatantra"                      : "Shastra",
    "Uḍḍāmareśvaratantra"               : "Shastra",
    "Vātūlanāthasūtras"                 : "Shastra",
    "Vātūlanāthasūtravṛtti"             : "Shastra",

    # ── PURANIC ──
    "Agnipurāṇa"                        : "Puranic",
    "Bhāgavatapurāṇa"                   : "Puranic",
    "Devīkālottarāgama"                 : "Puranic",
    "Garuḍapurāṇa"                      : "Puranic",
    "Gokarṇapurāṇasāraḥ"               : "Puranic",
    "Kālikāpurāṇa"                      : "Puranic",
    "Kūrmapurāṇa"                       : "Puranic",
    "Liṅgapurāṇa"                       : "Puranic",
    "Maṇimāhātmya"                      : "Puranic",
    "Matsyapurāṇa"                      : "Puranic",
    "Narasiṃhapurāṇa"                   : "Puranic",
    "Skandapurāṇa"                      : "Puranic",
    "Skandapurāṇa (Revākhaṇḍa)"        : "Puranic",
    "Śivapurāṇa"                        : "Puranic",
    "Varāhapurāṇa"                      : "Puranic",
    "Viṣṇupurāṇa"                       : "Puranic",
    "Kṛṣṇāmṛtamahārṇava"               : "Puranic",
}